import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  tutorialSidebar: [
    { type: "doc", id: "intro", label: "Introduction" },

    {
      type: "category",
      label: "Sales",
      collapsed: true,
      items: [
        { type: "doc", id: "crm/lead", label: "Lead" },
        { type: "doc", id: "crm/account", label: "Account" },
        { type: "doc", id: "crm/contact", label: "Contact" },
        { type: "doc", id: "crm/opportunity", label: "Opportunity" },
      ],
    },

    {
      type: "category",
      label: "Marketing",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "marketing/campaign-audience",
          label: "Audience",
        },
        { type: "doc", id: "marketing/campaign", label: "Campaign" },
        {
          type: "category",
          label: "Social",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "marketing/social/social-monitoring",
              label: "Social Monitoring",
            },
            {
              type: "doc",
              id: "marketing/social/media-library",
              label: "Media Library",
            },
          ],
        },
        {
          type: "category",
          label: "Components",
          collapsed: true,
          items: [
            { type: "doc", id: "marketing/components/asset", label: "Asset" },
            {
              type: "doc",
              id: "marketing/components/landing-page",
              label: "Landing Page",
            },
            {
              type: "doc",
              id: "marketing/components/form-builder",
              label: "Form Builder",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Analytics",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Insights",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "analytics/sales-dashboard",
              label: "Sales Dashboard",
            },
            {
              type: "doc",
              id: "analytics/marketing-dashboard",
              label: "Marketing Dashboard",
            },
            {
              type: "doc",
              id: "analytics/platform-usage",
              label: "Platform Usage",
            },
          ],
        },
        {
          type: "category",
          label: "Reports",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "analytics/sales-report",
              label: "Sales Report",
            },
            {
              type: "doc",
              id: "analytics/marketing-report",
              label: "Marketing Report",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Account Management",
      collapsed: true,
      items: [
        { type: "doc", id: "account-management/user", label: "User" },
        { type: "doc", id: "account-management/group", label: "Group" },
      ],
    },

    {
      type: "category",
      label: "System Configure",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "system-config/notification-content",
          label: "Notification Content",
        },

        { type: "doc", id: "system-config/lead", label: "Lead" },
        {
          type: "doc",
          id: "system-config/opportunities",
          label: "Opportunities",
        },
        {
          type: "doc",
          id: "system-config/account-type",
          label: "Account Type",
        },
        { type: "doc", id: "system-config/category", label: "Category" },
        {
          type: "doc",
          id: "system-config/campaign-attributes",
          label: "Campaign Attributes",
        },
        { type: "doc", id: "system-config/asset-type", label: "Asset Type" },
      ],
    },

    {
      type: "category",
      label: "Miscellaneous",
      collapsed: true,
      items: [
        { type: "doc", id: "miscellaneous/tasks", label: "Tasks" },
        { type: "doc", id: "miscellaneous/notes", label: "Notes" },
        { type: "doc", id: "miscellaneous/lead-alerts", label: "Lead Alerts" },
        {
          type: "doc",
          id: "miscellaneous/launch-guide",
          label: "Launch Guide",
        },
        { type: "doc", id: "miscellaneous/videos", label: "Videos" },
        {
          type: "doc",
          id: "miscellaneous/user-profile",
          label: "User Profile",
        },
      ],
    },
  ],
};

export default sidebars;
