import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  tutorialSidebar: [
    { type: "doc", id: "intro", label: "Introduction" },
    {
      type: "category",
      label: "Sales",
      items: [
        { type: "doc", id: "crm/lead", label: "Lead" },
        { type: "doc", id: "crm/account", label: "Account" },
        { type: "doc", id: "crm/contact", label: "Contact" },
        { type: "doc", id: "crm/opportunity", label: "Opportunity" },
      ],
    },
    {
      type: "category",
      label: "Marketing",
      items: [
        {
          type: "doc",
          id: "marketing/campaign-audience",
          label: "Campaign Audience",
        },
        {
          type: "doc",
          id: "marketing/campaign",
          label: "Campaign Management",
        },
        { type: "doc", id: "marketing/asset", label: "Asset" },
        { type: "doc", id: "marketing/landing-page", label: "Landing Page" },
        { type: "doc", id: "marketing/form-builder", label: "Form Builder" },
        { type: "doc", id: "marketing/media-library", label: "Media Library" },
        {
          type: "doc",
          id: "marketing/social-monitoring",
          label: "Social Monitoring",
        },
      ],
    },
    {
      type: "category",
      label: "Analytics",
      items: [
        {
          type: "category",
          label: "Insights",
          items: [
            {
              type: "doc",
              id: "analytics/sales-dashboard",
              label: "Sales Dashboard",
            },
            {
              type: "doc",
              id: "analytics/marketing-dashboard",
              label: "Marketing Dashboard",
            },
            {
              type: "doc",
              id: "analytics/platform-usage",
              label: "Platform Usage",
            },
          ],
        },
        {
          type: "category",
          label: "Reports",
          items: [
            {
              type: "doc",
              id: "analytics/sales-report",
              label: "Sales Report",
            },
            {
              type: "doc",
              id: "analytics/marketing-report",
              label: "Marketing Report",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Account Management",
      items: [
        { type: "doc", id: "account/user", label: "User" },
        { type: "doc", id: "account/group", label: "Group" },
      ],
    },
    {
      type: "category",
      label: "System Configure",
      items: [
        { type: "doc", id: "account/system-config", label: "System Config" },
      ],
    },
    {
      type: "category",
      label: "Miscellaneous",
      items: [
        { type: "doc", id: "account/tasks", label: "Tasks" },
        { type: "doc", id: "account/notes", label: "Notes" },
        { type: "doc", id: "account/lead-alerts", label: "Lead Alerts" },
        { type: "doc", id: "account/launch-guide", label: "Launch Guide" },
        { type: "doc", id: "account/videos", label: "Videos" },
      ],
    },
  ],
};

export default sidebars;
